services:
  chatbot:
    build: .
    container_name: ai_api_server
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true